#!/usr/bin/env node

/**
 * Custom build script for Vercel deployment
 * Handles React Router 7 + Hono server setup with database migrations
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('🚀 Starting Vercel build process...');
console.log('📅', new Date().toISOString());

try {
  // 1. Validate environment variables
  console.log('\n🔍 Validating environment variables...');
  const requiredEnvVars = ['DATABASE_URL', 'AUTH_SECRET'];
  const missingVars = requiredEnvVars.filter(varName => !process.env[varName]);
  
  if (missingVars.length > 0) {
    console.warn('⚠️  Missing environment variables:', missingVars.join(', '));
    console.warn('⚠️  Build will continue, but application may not work correctly');
  } else {
    console.log('✅ All required environment variables present');
  }

  // 2. Skip dependency installation (Vercel already handles this)
  console.log('\n📦 Dependencies already installed by Vercel');
  console.log('✅ Skipping npm install');

  // 3. Run database migrations
  console.log('\n🗄️  Running database migrations...');
  try {
    execSync('node scripts/migrate.js', { 
      stdio: 'inherit',
      env: { ...process.env }
    });
    console.log('✅ Database migrations completed');
  } catch (migrationError) {
    console.error('❌ Migration failed:', migrationError.message);
    console.warn('⚠️  Continuing build despite migration failure');
    console.warn('⚠️  Migrations will run on first application start');
  }

  // 4. Run React Router build
  console.log('\n🏗️  Building React Router application...');
  execSync('./node_modules/.bin/react-router build', { stdio: 'inherit' });
  console.log('✅ React Router build completed');

  // 5. Verify build directories
  console.log('\n🔍 Verifying build artifacts...');
  const buildDir = path.join(process.cwd(), 'build');
  const serverDir = path.join(buildDir, 'server');
  const clientDir = path.join(buildDir, 'client');

  if (!fs.existsSync(buildDir)) {
    throw new Error('Build directory not found');
  }

  if (!fs.existsSync(serverDir)) {
    throw new Error('Server build directory not found');
  }

  if (!fs.existsSync(clientDir)) {
    throw new Error('Client build directory not found');
  }

  console.log('✅ Build artifacts verified');

  // 6. Create api directory if it doesn't exist
  const apiDir = path.join(process.cwd(), 'api');
  if (!fs.existsSync(apiDir)) {
    fs.mkdirSync(apiDir, { recursive: true });
    console.log('✅ Created api directory');
  }

  // 7. Create Vercel serverless function wrapper
  console.log('\n📝 Creating Vercel function wrapper...');
  
  const functionWrapper = `/**
 * Vercel Serverless Function Handler
 * Generated by vercel-build.js
 * Date: ${new Date().toISOString()}
 */

const path = require('path');

// Import the Hono server
let server;

try {
  // Import the built server from __create
  const serverModule = require('../__create/index.ts');
  server = serverModule.default || serverModule;
  
  if (!server || typeof server.fetch !== 'function') {
    throw new Error('Invalid server export - missing fetch method');
  }
  
  console.log('✅ Server loaded successfully');
} catch (error) {
  console.error('❌ Failed to import server:', error);
  
  // Fallback handler for initialization errors
  module.exports = async (req, res) => {
    console.error('Server initialization failed:', error.message);
    res.status(500).json({ 
      error: 'Server initialization failed',
      message: error.message,
      timestamp: new Date().toISOString()
    });
  };
  return;
}

/**
 * Convert Vercel IncomingMessage to Web API Request
 */
function createWebRequest(req) {
  const protocol = req.headers['x-forwarded-proto'] || 'https';
  const host = req.headers['x-forwarded-host'] || req.headers.host;
  const url = new URL(req.url, \`\${protocol}://\${host}\`);
  
  const headers = new Headers();
  Object.entries(req.headers).forEach(([key, value]) => {
    if (value) {
      headers.set(key, Array.isArray(value) ? value.join(', ') : value);
    }
  });
  
  const init = {
    method: req.method,
    headers: headers,
  };
  
  // Add body for non-GET/HEAD requests
  if (req.method !== 'GET' && req.method !== 'HEAD' && req.body) {
    init.body = typeof req.body === 'string' ? req.body : JSON.stringify(req.body);
  }
  
  return new Request(url.toString(), init);
}

/**
 * Convert Web API Response to Vercel ServerResponse
 */
async function sendWebResponse(webResponse, res) {
  // Set status
  res.status(webResponse.status);
  
  // Set headers
  webResponse.headers.forEach((value, key) => {
    res.setHeader(key, value);
  });
  
  // Send body
  const contentType = webResponse.headers.get('content-type') || '';
  
  if (contentType.includes('application/json')) {
    const json = await webResponse.json();
    res.json(json);
  } else if (contentType.includes('text/')) {
    const text = await webResponse.text();
    res.send(text);
  } else {
    const buffer = Buffer.from(await webResponse.arrayBuffer());
    res.send(buffer);
  }
}

/**
 * Main Vercel handler
 */
module.exports = async (req, res) => {
  const startTime = Date.now();
  
  try {
    // Create Web API Request
    const webRequest = createWebRequest(req);
    
    // Handle with Hono server
    const webResponse = await server.fetch(webRequest);
    
    // Send Web API Response
    await sendWebResponse(webResponse, res);
    
    // Log request
    const duration = Date.now() - startTime;
    console.log(\`\${req.method} \${req.url} - \${webResponse.status} (\${duration}ms)\`);
    
  } catch (error) {
    console.error('❌ Handler error:', error);
    console.error('Stack:', error.stack);
    
    // Send error response
    if (!res.headersSent) {
      res.status(500).json({ 
        error: 'Internal Server Error',
        message: error.message,
        timestamp: new Date().toISOString()
      });
    }
  }
};
`;

  fs.writeFileSync(path.join(apiDir, 'index.js'), functionWrapper);
  console.log('✅ Vercel function wrapper created');

  // 8. Create .vercelignore if it doesn't exist
  const vercelIgnorePath = path.join(process.cwd(), '.vercelignore');
  if (!fs.existsSync(vercelIgnorePath)) {
    const vercelIgnore = `node_modules
.env
.env.local
.DS_Store
*.log
.cache
.turbo
coverage
.next
dist
.vercel
`;
    fs.writeFileSync(vercelIgnorePath, vercelIgnore);
    console.log('✅ Created .vercelignore');
  }

  // 9. Display build summary
  console.log('\n📊 Build Summary:');
  console.log('   ✅ Environment variables validated');
  console.log('   ✅ Database migrations executed');
  console.log('   ✅ React Router build completed');
  console.log('   ✅ Vercel function created');
  console.log('\n📁 Build artifacts:');
  console.log(`   - Client: ${clientDir}`);
  console.log(`   - Server: ${serverDir}`);
  console.log(`   - Function: ${path.join(apiDir, 'index.js')}`);
  
  console.log('\n✅ Build completed successfully!');
  console.log('🎉 Ready for deployment to Vercel');

} catch (error) {
  console.error('\n❌ Build failed:', error.message);
  console.error('Stack:', error.stack);
  process.exit(1);
}
